using System.Collections.Generic;

namespace CaptureApp.Models;

public static class WhisperLanguageCatalog
{
    public static IReadOnlyList<LanguageOption> Languages { get; } = new List<LanguageOption>
    {
        new("en", "English"),
        new("es", "Spanish"),
        new("fr", "French"),
        new("de", "German"),
        new("it", "Italian"),
        new("pt", "Portuguese"),
        new("ru", "Russian"),
        new("zh", "Chinese"),
        new("ja", "Japanese"),
        new("ko", "Korean"),
        new("ar", "Arabic"),
        new("hi", "Hindi"),
        new("bn", "Bengali"),
        new("ur", "Urdu"),
        new("tr", "Turkish"),
        new("vi", "Vietnamese"),
        new("th", "Thai"),
        new("id", "Indonesian"),
        new("pl", "Polish"),
        new("uk", "Ukrainian"),
        new("sv", "Swedish"),
        new("nl", "Dutch"),
        new("fi", "Finnish"),
        new("no", "Norwegian"),
        new("da", "Danish"),
        new("cs", "Czech"),
        new("el", "Greek"),
        new("he", "Hebrew"),
        new("fa", "Persian"),
        new("ro", "Romanian"),
        new("hu", "Hungarian"),
        new("bg", "Bulgarian"),
        new("sr", "Serbian"),
        new("hr", "Croatian"),
        new("sk", "Slovak"),
        new("sl", "Slovenian"),
        new("lt", "Lithuanian"),
        new("lv", "Latvian"),
        new("et", "Estonian"),
        new("ms", "Malay"),
        new("ta", "Tamil"),
        new("te", "Telugu"),
        new("ml", "Malayalam"),
        new("mr", "Marathi"),
        new("gu", "Gujarati"),
        new("pa", "Punjabi"),
        new("kn", "Kannada"),
        new("si", "Sinhala"),
        new("ne", "Nepali"),
        new("sw", "Swahili"),
        new("am", "Amharic"),
        new("zu", "Zulu"),
        new("xh", "Xhosa"),
        new("af", "Afrikaans"),
        new("is", "Icelandic"),
        new("ga", "Irish"),
        new("cy", "Welsh"),
        new("mt", "Maltese"),
        new("mk", "Macedonian"),
        new("hy", "Armenian"),
        new("ka", "Georgian"),
        new("sq", "Albanian"),
        new("la", "Latin"),
        new("eo", "Esperanto"),
        new("yo", "Yoruba"),
        new("ig", "Igbo"),
        new("ha", "Hausa")
    };
}
